const BASE_URL = "http://18.207.247.235"

export const LOGIN_URL = BASE_URL + "/login"
export const TRAINING_BY_USER = BASE_URL + "/user/trainings"
export const PERSONAL_TRAINERS_LIST = BASE_URL + "/listPersonals"
export const RESETPASSWORD_URL = BASE_URL + "/login/reset"
export const REGISTER_USER_URL = BASE_URL + "/register/user"
export const REGISTER_PERSONAL_URL = BASE_URL + "/register/personal"
export const ACCOUNT_USER_URL = BASE_URL + "/account/user"
export const ACCOUNT_PERSONAL_URL = BASE_URL + "/account/personal"