export default {
  BACKGROUND: "#D6D6D6",
  FOOTER_BACKGROUND: "#2E2E2E",
  FOOTER_TEXT: "#BDBDBD",
  BUTTON_BACKGROUND: "#2E2E2E",
  BUTTON_TEXT: "#fff",
  NAVIGATION_HEADER_BACKGROUND: "#2E2E2E",
  NAVIGATION_HEADER_TEXT: "#fff",
  TABS_BACKGROUND: "#F2F2F2",
  TABS_TEXT: "#2E2E2E",
  INPUT_BACKGROUND: "#B6B6B6",
  SAFE_AREA: "#2E2E2E",
  TEXT: "#2E2E2E",
};
